<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <VersionPrefix>1.2</VersionPrefix>
    <Version>1.2</Version>
    <ProductVersion>1.2</ProductVersion>
    <IwashiScopeBuildNumber>82</IwashiScopeBuildNumber>
    <AssemblyVersion>1.2.0.$(IwashiScopeBuildNumber)</AssemblyVersion>
    <FileVersion>1.2.0.$(IwashiScopeBuildNumber)</FileVersion>
    <InformationalVersion>1.2</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Authors>Yamonov</Authors>
    <Product>IwashiScope</Product>
    <Copyright>Copyright © Yamonov</Copyright>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyMetadata Include="BuildNumber" Value="$(IwashiScopeBuildNumber)" />
  </ItemGroup>
</Project>
