#!/usr/bin/env swift
// SPDX-FileCopyrightText: 2026 Yamonov
// SPDX-License-Identifier: AGPL-3.0-only
// Uses the same checksum-first generation approach as the illuminant generator.

import CryptoKit
import Foundation

enum GenerationError: Error {
    case invalidArguments, invalidSource, outdatedOutput
}

let arguments = Array(CommandLine.arguments.dropFirst())
guard arguments.isEmpty || arguments == ["--check"] else { throw GenerationError.invalidArguments }
let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
let input = root.appendingPathComponent("ThirdParty/CIE/CIE_lms_cf_2deg.csv")
let metadataURL = root.appendingPathComponent("ThirdParty/CIE/CIE_lms_cf_2deg.csv_metadata.json")
let output = root.appendingPathComponent("IwashiScopePackage/Sources/IwashiScopeFeature/Models/CIE2006LMSData.generated.swift")
let csharpOutput = root.appendingPathComponent("Windows/src/IwashiScope.Core/Calculations/Cie2006LmsData.generated.cs")
let data = try Data(contentsOf: input)
let sha256 = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
let md5 = Insecure.MD5.hash(data: data).map { String(format: "%02x", $0) }.joined()
let expectedSHA256 = "f48160edf11c1a121aaaf41d4c3b7513385bfc9c60d726b88e735519f6d37b1f"
let expectedMD5 = "dba2e9d1f5e6667575aa069832159510"
guard sha256 == expectedSHA256, md5 == expectedMD5,
      let metadata = try JSONSerialization.jsonObject(with: Data(contentsOf: metadataURL)) as? [String: Any],
      let checksums = metadata["checksums"] as? [[String: String]],
      checksums.contains(where: { $0["hashMethod"] == "sha256" && $0["checksum"] == expectedSHA256 }),
      checksums.contains(where: { $0["hashMethod"] == "md5" && $0["checksum"] == expectedMD5 }),
      let source = String(data: data, encoding: .utf8) else {
    throw GenerationError.invalidSource
}

let rows = source.split(whereSeparator: \.isNewline).map {
    $0.split(separator: ",", omittingEmptySubsequences: false).map(String.init)
}
guard rows.count == 89 else { throw GenerationError.invalidSource }
var columns = [[String]](repeating: [], count: 3)
for (index, row) in rows.enumerated() {
    let wavelength = 390 + index * 5
    guard row.count == 4, Int(row[0]) == wavelength else { throw GenerationError.invalidSource }
    for cone in 0..<3 {
        if cone == 2 && wavelength > 615 {
            guard row[cone + 1] == "NaN" else { throw GenerationError.invalidSource }
            continue
        }
        guard let value = Double(row[cone + 1]), value.isFinite, value >= 0 else {
            throw GenerationError.invalidSource
        }
        columns[cone].append(row[cone + 1])
    }
}
guard columns.map(\.count) == [89, 89, 46],
      rows[31] == ["545", "0.919073", "0.9971948", "0.003168911"] else {
    throw GenerationError.invalidSource
}

let names = ["long", "medium", "short"]
let arrays = zip(names, columns).map { name, values in
    let lines = stride(from: 0, to: values.count, by: 6).map { start in
        "        " + values[start..<min(start + 6, values.count)].joined(separator: ", ") + ","
    }.joined(separator: "\n")
    return "    static let \(name): [Double] = [\n\(lines)\n    ]"
}.joined(separator: "\n\n")

let generated = """
/*
 SPDX-FileCopyrightText: 2026 Yamonov
 SPDX-License-Identifier: GPL-3.0-only

 Generated by Scripts/generate-cie-2006-lms.swift. Do not edit by hand.
 Source: CIE 2006 LMS cone fundamentals, 2-degree field, energy basis.
 CIE 170-1:2006, Table 6.7. DOI: 10.25039/CIE.DS.tijidesg
 Creator and publisher: International Commission on Illumination (CIE), Vienna, AT.
 Original data: CC BY-SA 4.0, https://creativecommons.org/licenses/by-sa/4.0/
 CSV SHA-256: \(expectedSHA256)
 Adaptation date: 2026-09-22
 Transformation: express the original finite 5 nm samples as Swift arrays.
 L/M: 390...830 nm; S: 390...615 nm. Undefined S entries are not included.
 No interpolation or peak normalization is applied to these source arrays.

 Yamonov's contributions to this adaptation are GPL-3.0-only under the
 one-way BY-SA Compatible License mechanism. Both CC BY-SA 4.0 and
 GPL-3.0-only apply to the adapted material. When combined with IwashiScope,
 GPL-3.0-only governs this adaptation and AGPL-3.0-only governs IwashiScope
 under section 13 of GPLv3 and AGPLv3. See ThirdParty/CIE/README.md.
 */

enum CIE2006LMSData {
    static let firstWavelength = 390.0
    static let interval = 5.0

\(arrays)
}

"""

let csharpArrays = zip(["Long", "Medium", "Short"], columns).map { name, values in
    let lines = stride(from: 0, to: values.count, by: 6).map { start in
        "        " + values[start..<min(start + 6, values.count)].joined(separator: ", ") + ","
    }.joined(separator: "\n")
    return "    internal static readonly double[] \(name) =\n    [\n\(lines)\n    ];"
}.joined(separator: "\n\n")
guard let declaration = generated.range(of: "\nenum CIE2006LMSData") else { throw GenerationError.invalidSource }
let csharpHeader = String(generated[..<declaration.lowerBound])
    .replacingOccurrences(of: "as Swift arrays.", with: "as C# arrays.")
let generatedCSharp = """
\(csharpHeader)
namespace IwashiScope.Core.Calculations;

internal static class Cie2006LmsData
{
    internal const double FirstWavelength = 390.0;
    internal const double Interval = 5.0;

\(csharpArrays)
}

"""

for (destination, contents) in [(output, generated), (csharpOutput, generatedCSharp)] {
    if arguments == ["--check"] {
        guard try String(contentsOf: destination, encoding: .utf8) == contents else {
            throw GenerationError.outdatedOutput
        }
    } else {
        try contents.write(to: destination, atomically: true, encoding: .utf8)
    }
}
if arguments == ["--check"] {
    print("CIE 2006 LMS source checksums and Swift/C# arrays are up to date.")
} else {
    print("Generated CIE2006LMSData.generated.swift and Cie2006LmsData.generated.cs from verified CIE source data.")
}
